# Generated by Django 5.2.17 on 2026-08-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('group', 'Group Tours'), ('individual', 'Individual Tours'), ('specialised', 'Specialised Tours')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['kind', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('destination', models.CharField(blank=True, max_length=120)),
                ('duration_label', models.CharField(blank=True, help_text='Shown on cards, e.g. 07 N / 08 D', max_length=80)),
                ('nights', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True)),
                ('itinerary', models.TextField(blank=True, help_text='Day-wise itinerary (plain text or HTML)')),
                ('cost_includes', models.TextField(blank=True)),
                ('cost_excludes', models.TextField(blank=True)),
                ('offers', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='tours/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in homepage Available Tours')),
                ('is_latest_excursion', models.BooleanField(default=False, help_text='Show in homepage Latest Excursion')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.category')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children_5_12', models.PositiveSmallIntegerField(default=0)),
                ('children_below_5', models.PositiveSmallIntegerField(default=0)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='tours.tour')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional per-person price', max_digits=10, null=True)),
                ('seats', models.PositiveSmallIntegerField(blank=True, help_text='Seats remaining (optional)', null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Tour date',
                'verbose_name_plural': 'Tour dates',
                'ordering': ['start_date'],
            },
        ),
    ]
